image_width: 640
image_height: 360
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [333.26084,   0.     , 315.3434 ,
           0.     , 330.25227, 172.41486,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.028031, -0.003357, 0.012149, -0.028142, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [341.33133,   0.     , 289.13793,   0.     ,
           0.     , 353.2681 , 177.85027,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
